/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {},
  },
  plugins: [],
  safelist: [
    'shadow-white',
    'shadow-blue-500',
    'shadow-gray-500',
    'shadow-red-500',
    'shadow-orange-500',
    'shadow-yellow-500',
    'shadow-green-500',
    'shadow-blue-500',
    'shadow-violet-500',
    'shadow-purple-500',
    'shadow-pink-500',
    'hover:shadow-white',
    'hover:shadow-blue-500',
    'hover:shadow-gray-500',
    'hover:shadow-red-500',
    'hover:shadow-orange-500',
    'hover:shadow-yellow-500',
    'hover:shadow-green-500',
    'hover:shadow-blue-500',
    'hover:shadow-violet-500',
    'hover:shadow-purple-500',
    'hover:shadow-pink-500',
  ],
};
